#!/bin/bash

[ "$1" = "usage" ] && exit 0

item="$2"

TASK=$(sed "$item!d" "$TODO_FILE")

# Take into account "del #ITEM TERM"
if [ -z "$3" ]; then
    getTodo "$item"
fi

"$TODO_SH" command "$@"

python "$TODO_ACTIONS_DIR"/recur.py "$TASK"
