#!/bin/bash

# v0.0.1

action=$1
shift

[ "$action" = "usage" ] && {
  echo ""
  echo "  Reschedule overdue tasks for today:"
  echo "    mover"
  echo ""
  exit
}
[ "$action" = "mover" ] && {
    $TODO_FULL_SH ls | python $TODO_ACTIONS_DIR/mover.py
}
